FROM golang:1.24-alpine AS gobuild
WORKDIR /build-dir
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o /tmp/bridge3 github.com/tonkeeper/bridge/cmd/bridge3


FROM scratch AS bridge
COPY --from=gobuild /tmp/bridge3 /app/bridge3
CMD ["/app/bridge3"]
