services:
  bridge:
    container_name: bridge
    build: .
    environment:
      PORT: 8081
      CORS_ENABLE: "true"
      HEARTBEAT_INTERVAL: 10
      RPS_LIMIT: 100000
      CONNECTIONS_LIMIT: 100000
      LOG_LEVEL: error
      PPROF_ENABLED: "true"
    ports:
      - "8081:8081"  # bridge
      - "9103:9103"  # pprof and metrics
    networks:
      - bridge_network
    restart: unless-stopped

  integration:
    build:
      context: .
      dockerfile: Dockerfile.integration
    container_name: bridge-integration
    environment:
      BRIDGE_URL: "http://bridge:8081/bridge"
    depends_on:
      bridge:
        condition: service_started
    networks:
      - bridge_network
    command: [ "/bin/bash", "-c", "make test-bridge-sdk" ]
    # command: ["/bin/bash", "-c", "tail -f /dev/null"]

  gointegration:
    build:
      context: .
      dockerfile: Dockerfile.gointegration
    container_name: bridge-gointegration
    environment:
      BRIDGE_URL: "http://bridge:8081/bridge"
    depends_on:
      bridge:
        condition: service_started
    networks:
      - bridge_network
    command: [ "/bin/bash", "-c", "make test-gointegration" ]
    # command: ["/bin/bash", "-c", "tail -f /dev/null"]

  benchmark:
    build:
      context: .
      dockerfile: benchmark/Benchmark.Dockerfile
    working_dir: /scripts
    environment:
      BRIDGE_URL: "http://bridge:8081/bridge"
      TEST_DURATION: "10s"
      SSE_VUS: "100"
      SEND_RATE: "2500"
    depends_on:
      bridge:
        condition: service_started
    networks:
      - bridge_network
    volumes:
      - ./benchmark:/scripts:ro
      - ./benchmark/results:/results
    entrypoint: [ "/bin/sh", "-lc" ]
    command:
      - >
        printf '\n\n====== pprof BEFORE ======\n\n';
        pprof -top -sample_index=alloc_space -nodecount=5 http://bridge:9103/debug/pprof/allocs || true;
        printf '\n\n==========================\n\n';
        /usr/local/bin/k6 run --summary-export=/results/summary.json /scripts/bridge_test.js;
        printf '\n\n====== pprof AFTER ======\n\n';
        pprof -top -sample_index=alloc_space -nodecount=5 http://bridge:9103/debug/pprof/allocs || true;
        printf '\n\n==========================\n\n';


networks:
  bridge_network:
    driver: bridge
