FROM golang:1.24-alpine AS gobuild
RUN apk add --no-cache make git
WORKDIR /build-dir
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN make build3 && cp bridge3 /tmp/bridge3


FROM alpine:latest AS bridge
COPY --from=gobuild /tmp/bridge3 /app/bridge3
CMD ["/app/bridge3"]
