// Package tonmetrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package tonmetrics

// Defines values for BridgeClientConnectErrorEventClientEnvironment.
const (
	BridgeClientConnectErrorEventClientEnvironmentBridge BridgeClientConnectErrorEventClientEnvironment = "bridge"
	BridgeClientConnectErrorEventClientEnvironmentEmpty  BridgeClientConnectErrorEventClientEnvironment = ""
)

// Defines values for BridgeClientConnectErrorEventEventName.
const (
	BridgeClientConnectErrorEventEventNameBridgeClientConnectError BridgeClientConnectErrorEventEventName = "bridge-client-connect-error"
	BridgeClientConnectErrorEventEventNameEmpty                    BridgeClientConnectErrorEventEventName = ""
)

// Defines values for BridgeClientConnectErrorEventSubsystem.
const (
	BridgeClientConnectErrorEventSubsystemBridge    BridgeClientConnectErrorEventSubsystem = "bridge"
	BridgeClientConnectErrorEventSubsystemDapp      BridgeClientConnectErrorEventSubsystem = "dapp"
	BridgeClientConnectErrorEventSubsystemDappSdk   BridgeClientConnectErrorEventSubsystem = "dapp-sdk"
	BridgeClientConnectErrorEventSubsystemWallet    BridgeClientConnectErrorEventSubsystem = "wallet"
	BridgeClientConnectErrorEventSubsystemWalletSdk BridgeClientConnectErrorEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeClientConnectStartedEventClientEnvironment.
const (
	BridgeClientConnectStartedEventClientEnvironmentBridge BridgeClientConnectStartedEventClientEnvironment = "bridge"
	BridgeClientConnectStartedEventClientEnvironmentEmpty  BridgeClientConnectStartedEventClientEnvironment = ""
)

// Defines values for BridgeClientConnectStartedEventEventName.
const (
	BridgeClientConnectStartedEventEventNameBridgeClientConnectStarted BridgeClientConnectStartedEventEventName = "bridge-client-connect-started"
	BridgeClientConnectStartedEventEventNameEmpty                      BridgeClientConnectStartedEventEventName = ""
)

// Defines values for BridgeClientConnectStartedEventSubsystem.
const (
	BridgeClientConnectStartedEventSubsystemBridge    BridgeClientConnectStartedEventSubsystem = "bridge"
	BridgeClientConnectStartedEventSubsystemDapp      BridgeClientConnectStartedEventSubsystem = "dapp"
	BridgeClientConnectStartedEventSubsystemDappSdk   BridgeClientConnectStartedEventSubsystem = "dapp-sdk"
	BridgeClientConnectStartedEventSubsystemWallet    BridgeClientConnectStartedEventSubsystem = "wallet"
	BridgeClientConnectStartedEventSubsystemWalletSdk BridgeClientConnectStartedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeClientMessageDecodeErrorEventClientEnvironment.
const (
	BridgeClientMessageDecodeErrorEventClientEnvironmentBridge BridgeClientMessageDecodeErrorEventClientEnvironment = "bridge"
	BridgeClientMessageDecodeErrorEventClientEnvironmentEmpty  BridgeClientMessageDecodeErrorEventClientEnvironment = ""
)

// Defines values for BridgeClientMessageDecodeErrorEventEventName.
const (
	BridgeClientMessageDecodeErrorEventEventNameBridgeClientMessageDecodeError BridgeClientMessageDecodeErrorEventEventName = "bridge-client-message-decode-error"
	BridgeClientMessageDecodeErrorEventEventNameEmpty                          BridgeClientMessageDecodeErrorEventEventName = ""
)

// Defines values for BridgeClientMessageDecodeErrorEventSubsystem.
const (
	BridgeClientMessageDecodeErrorEventSubsystemBridge    BridgeClientMessageDecodeErrorEventSubsystem = "bridge"
	BridgeClientMessageDecodeErrorEventSubsystemDapp      BridgeClientMessageDecodeErrorEventSubsystem = "dapp"
	BridgeClientMessageDecodeErrorEventSubsystemDappSdk   BridgeClientMessageDecodeErrorEventSubsystem = "dapp-sdk"
	BridgeClientMessageDecodeErrorEventSubsystemWallet    BridgeClientMessageDecodeErrorEventSubsystem = "wallet"
	BridgeClientMessageDecodeErrorEventSubsystemWalletSdk BridgeClientMessageDecodeErrorEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeClientMessageReceivedEventClientEnvironment.
const (
	BridgeClientMessageReceivedEventClientEnvironmentBridge BridgeClientMessageReceivedEventClientEnvironment = "bridge"
	BridgeClientMessageReceivedEventClientEnvironmentEmpty  BridgeClientMessageReceivedEventClientEnvironment = ""
)

// Defines values for BridgeClientMessageReceivedEventEventName.
const (
	BridgeClientMessageReceivedEventEventNameBridgeClientMessageReceived BridgeClientMessageReceivedEventEventName = "bridge-client-message-received"
	BridgeClientMessageReceivedEventEventNameEmpty                       BridgeClientMessageReceivedEventEventName = ""
)

// Defines values for BridgeClientMessageReceivedEventSubsystem.
const (
	BridgeClientMessageReceivedEventSubsystemBridge    BridgeClientMessageReceivedEventSubsystem = "bridge"
	BridgeClientMessageReceivedEventSubsystemDapp      BridgeClientMessageReceivedEventSubsystem = "dapp"
	BridgeClientMessageReceivedEventSubsystemDappSdk   BridgeClientMessageReceivedEventSubsystem = "dapp-sdk"
	BridgeClientMessageReceivedEventSubsystemWallet    BridgeClientMessageReceivedEventSubsystem = "wallet"
	BridgeClientMessageReceivedEventSubsystemWalletSdk BridgeClientMessageReceivedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeConnectEstablishedEventClientEnvironment.
const (
	BridgeConnectEstablishedEventClientEnvironmentBridge BridgeConnectEstablishedEventClientEnvironment = "bridge"
	BridgeConnectEstablishedEventClientEnvironmentEmpty  BridgeConnectEstablishedEventClientEnvironment = ""
)

// Defines values for BridgeConnectEstablishedEventEventName.
const (
	BridgeConnectEstablishedEventEventNameBridgeClientConnectEstablished BridgeConnectEstablishedEventEventName = "bridge-client-connect-established"
	BridgeConnectEstablishedEventEventNameEmpty                          BridgeConnectEstablishedEventEventName = ""
)

// Defines values for BridgeConnectEstablishedEventSubsystem.
const (
	BridgeConnectEstablishedEventSubsystemBridge    BridgeConnectEstablishedEventSubsystem = "bridge"
	BridgeConnectEstablishedEventSubsystemDapp      BridgeConnectEstablishedEventSubsystem = "dapp"
	BridgeConnectEstablishedEventSubsystemDappSdk   BridgeConnectEstablishedEventSubsystem = "dapp-sdk"
	BridgeConnectEstablishedEventSubsystemWallet    BridgeConnectEstablishedEventSubsystem = "wallet"
	BridgeConnectEstablishedEventSubsystemWalletSdk BridgeConnectEstablishedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeEventsClientSubscribedEventClientEnvironment.
const (
	BridgeEventsClientSubscribedEventClientEnvironmentBridge BridgeEventsClientSubscribedEventClientEnvironment = "bridge"
	BridgeEventsClientSubscribedEventClientEnvironmentEmpty  BridgeEventsClientSubscribedEventClientEnvironment = ""
)

// Defines values for BridgeEventsClientSubscribedEventEventName.
const (
	BridgeEventsClientSubscribedEventEventNameBridgeEventsClientSubscribed BridgeEventsClientSubscribedEventEventName = "bridge-events-client-subscribed"
	BridgeEventsClientSubscribedEventEventNameEmpty                        BridgeEventsClientSubscribedEventEventName = ""
)

// Defines values for BridgeEventsClientSubscribedEventSubsystem.
const (
	BridgeEventsClientSubscribedEventSubsystemBridge    BridgeEventsClientSubscribedEventSubsystem = "bridge"
	BridgeEventsClientSubscribedEventSubsystemDapp      BridgeEventsClientSubscribedEventSubsystem = "dapp"
	BridgeEventsClientSubscribedEventSubsystemDappSdk   BridgeEventsClientSubscribedEventSubsystem = "dapp-sdk"
	BridgeEventsClientSubscribedEventSubsystemWallet    BridgeEventsClientSubscribedEventSubsystem = "wallet"
	BridgeEventsClientSubscribedEventSubsystemWalletSdk BridgeEventsClientSubscribedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeEventsClientUnsubscribedEventClientEnvironment.
const (
	BridgeEventsClientUnsubscribedEventClientEnvironmentBridge BridgeEventsClientUnsubscribedEventClientEnvironment = "bridge"
	BridgeEventsClientUnsubscribedEventClientEnvironmentEmpty  BridgeEventsClientUnsubscribedEventClientEnvironment = ""
)

// Defines values for BridgeEventsClientUnsubscribedEventEventName.
const (
	BridgeEventsClientUnsubscribedEventEventNameBridgeEventsClientUnsubscribed BridgeEventsClientUnsubscribedEventEventName = "bridge-events-client-unsubscribed"
	BridgeEventsClientUnsubscribedEventEventNameEmpty                          BridgeEventsClientUnsubscribedEventEventName = ""
)

// Defines values for BridgeEventsClientUnsubscribedEventSubsystem.
const (
	BridgeEventsClientUnsubscribedEventSubsystemBridge    BridgeEventsClientUnsubscribedEventSubsystem = "bridge"
	BridgeEventsClientUnsubscribedEventSubsystemDapp      BridgeEventsClientUnsubscribedEventSubsystem = "dapp"
	BridgeEventsClientUnsubscribedEventSubsystemDappSdk   BridgeEventsClientUnsubscribedEventSubsystem = "dapp-sdk"
	BridgeEventsClientUnsubscribedEventSubsystemWallet    BridgeEventsClientUnsubscribedEventSubsystem = "wallet"
	BridgeEventsClientUnsubscribedEventSubsystemWalletSdk BridgeEventsClientUnsubscribedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeMessageExpiredEventClientEnvironment.
const (
	BridgeMessageExpiredEventClientEnvironmentBridge BridgeMessageExpiredEventClientEnvironment = "bridge"
	BridgeMessageExpiredEventClientEnvironmentEmpty  BridgeMessageExpiredEventClientEnvironment = ""
)

// Defines values for BridgeMessageExpiredEventEventName.
const (
	BridgeMessageExpiredEventEventNameBridgeMessageExpired BridgeMessageExpiredEventEventName = "bridge-message-expired"
	BridgeMessageExpiredEventEventNameEmpty                BridgeMessageExpiredEventEventName = ""
)

// Defines values for BridgeMessageExpiredEventSubsystem.
const (
	BridgeMessageExpiredEventSubsystemBridge    BridgeMessageExpiredEventSubsystem = "bridge"
	BridgeMessageExpiredEventSubsystemDapp      BridgeMessageExpiredEventSubsystem = "dapp"
	BridgeMessageExpiredEventSubsystemDappSdk   BridgeMessageExpiredEventSubsystem = "dapp-sdk"
	BridgeMessageExpiredEventSubsystemWallet    BridgeMessageExpiredEventSubsystem = "wallet"
	BridgeMessageExpiredEventSubsystemWalletSdk BridgeMessageExpiredEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeMessageReceivedEventClientEnvironment.
const (
	BridgeMessageReceivedEventClientEnvironmentBridge BridgeMessageReceivedEventClientEnvironment = "bridge"
	BridgeMessageReceivedEventClientEnvironmentEmpty  BridgeMessageReceivedEventClientEnvironment = ""
)

// Defines values for BridgeMessageReceivedEventEventName.
const (
	BridgeMessageReceivedEventEventNameBridgeMessageReceived BridgeMessageReceivedEventEventName = "bridge-message-received"
	BridgeMessageReceivedEventEventNameEmpty                 BridgeMessageReceivedEventEventName = ""
)

// Defines values for BridgeMessageReceivedEventSubsystem.
const (
	BridgeMessageReceivedEventSubsystemBridge    BridgeMessageReceivedEventSubsystem = "bridge"
	BridgeMessageReceivedEventSubsystemDapp      BridgeMessageReceivedEventSubsystem = "dapp"
	BridgeMessageReceivedEventSubsystemDappSdk   BridgeMessageReceivedEventSubsystem = "dapp-sdk"
	BridgeMessageReceivedEventSubsystemWallet    BridgeMessageReceivedEventSubsystem = "wallet"
	BridgeMessageReceivedEventSubsystemWalletSdk BridgeMessageReceivedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeMessageSentEventClientEnvironment.
const (
	BridgeMessageSentEventClientEnvironmentBridge BridgeMessageSentEventClientEnvironment = "bridge"
	BridgeMessageSentEventClientEnvironmentEmpty  BridgeMessageSentEventClientEnvironment = ""
)

// Defines values for BridgeMessageSentEventEventName.
const (
	BridgeMessageSentEventEventNameBridgeMessageSent BridgeMessageSentEventEventName = "bridge-message-sent"
	BridgeMessageSentEventEventNameEmpty             BridgeMessageSentEventEventName = ""
)

// Defines values for BridgeMessageSentEventSubsystem.
const (
	BridgeMessageSentEventSubsystemBridge    BridgeMessageSentEventSubsystem = "bridge"
	BridgeMessageSentEventSubsystemDapp      BridgeMessageSentEventSubsystem = "dapp"
	BridgeMessageSentEventSubsystemDappSdk   BridgeMessageSentEventSubsystem = "dapp-sdk"
	BridgeMessageSentEventSubsystemWallet    BridgeMessageSentEventSubsystem = "wallet"
	BridgeMessageSentEventSubsystemWalletSdk BridgeMessageSentEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeMessageValidationFailedEventClientEnvironment.
const (
	BridgeMessageValidationFailedEventClientEnvironmentBridge BridgeMessageValidationFailedEventClientEnvironment = "bridge"
	BridgeMessageValidationFailedEventClientEnvironmentEmpty  BridgeMessageValidationFailedEventClientEnvironment = ""
)

// Defines values for BridgeMessageValidationFailedEventEventName.
const (
	BridgeMessageValidationFailedEventEventNameBridgeMessageValidationFailed BridgeMessageValidationFailedEventEventName = "bridge-message-validation-failed"
	BridgeMessageValidationFailedEventEventNameEmpty                         BridgeMessageValidationFailedEventEventName = ""
)

// Defines values for BridgeMessageValidationFailedEventSubsystem.
const (
	BridgeMessageValidationFailedEventSubsystemBridge    BridgeMessageValidationFailedEventSubsystem = "bridge"
	BridgeMessageValidationFailedEventSubsystemDapp      BridgeMessageValidationFailedEventSubsystem = "dapp"
	BridgeMessageValidationFailedEventSubsystemDappSdk   BridgeMessageValidationFailedEventSubsystem = "dapp-sdk"
	BridgeMessageValidationFailedEventSubsystemWallet    BridgeMessageValidationFailedEventSubsystem = "wallet"
	BridgeMessageValidationFailedEventSubsystemWalletSdk BridgeMessageValidationFailedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeRequestSentEventClientEnvironment.
const (
	BridgeRequestSentEventClientEnvironmentBridge BridgeRequestSentEventClientEnvironment = "bridge"
	BridgeRequestSentEventClientEnvironmentEmpty  BridgeRequestSentEventClientEnvironment = ""
)

// Defines values for BridgeRequestSentEventEventName.
const (
	BridgeRequestSentEventEventNameBridgeClientMessageSent BridgeRequestSentEventEventName = "bridge-client-message-sent"
	BridgeRequestSentEventEventNameEmpty                   BridgeRequestSentEventEventName = ""
)

// Defines values for BridgeRequestSentEventSubsystem.
const (
	BridgeRequestSentEventSubsystemBridge    BridgeRequestSentEventSubsystem = "bridge"
	BridgeRequestSentEventSubsystemDapp      BridgeRequestSentEventSubsystem = "dapp"
	BridgeRequestSentEventSubsystemDappSdk   BridgeRequestSentEventSubsystem = "dapp-sdk"
	BridgeRequestSentEventSubsystemWallet    BridgeRequestSentEventSubsystem = "wallet"
	BridgeRequestSentEventSubsystemWalletSdk BridgeRequestSentEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeVerifyEventClientEnvironment.
const (
	BridgeVerifyEventClientEnvironmentBridge BridgeVerifyEventClientEnvironment = "bridge"
	BridgeVerifyEventClientEnvironmentEmpty  BridgeVerifyEventClientEnvironment = ""
)

// Defines values for BridgeVerifyEventEventName.
const (
	BridgeVerifyEventEventNameBridgeVerify BridgeVerifyEventEventName = "bridge-verify"
	BridgeVerifyEventEventNameEmpty        BridgeVerifyEventEventName = ""
)

// Defines values for BridgeVerifyEventSubsystem.
const (
	BridgeVerifyEventSubsystemBridge    BridgeVerifyEventSubsystem = "bridge"
	BridgeVerifyEventSubsystemDapp      BridgeVerifyEventSubsystem = "dapp"
	BridgeVerifyEventSubsystemDappSdk   BridgeVerifyEventSubsystem = "dapp-sdk"
	BridgeVerifyEventSubsystemWallet    BridgeVerifyEventSubsystem = "wallet"
	BridgeVerifyEventSubsystemWalletSdk BridgeVerifyEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeVerifyEventVerifyType.
const (
	BridgeVerifyEventVerifyTypeConnect BridgeVerifyEventVerifyType = "connect"
)

// Defines values for BridgeVerifyValidationFailedEventClientEnvironment.
const (
	BridgeVerifyValidationFailedEventClientEnvironmentBridge BridgeVerifyValidationFailedEventClientEnvironment = "bridge"
	BridgeVerifyValidationFailedEventClientEnvironmentEmpty  BridgeVerifyValidationFailedEventClientEnvironment = ""
)

// Defines values for BridgeVerifyValidationFailedEventEventName.
const (
	BridgeVerifyValidationFailed BridgeVerifyValidationFailedEventEventName = "bridge-verify-validation-failed"
	Empty                        BridgeVerifyValidationFailedEventEventName = ""
)

// Defines values for BridgeVerifyValidationFailedEventSubsystem.
const (
	Bridge    BridgeVerifyValidationFailedEventSubsystem = "bridge"
	Dapp      BridgeVerifyValidationFailedEventSubsystem = "dapp"
	DappSdk   BridgeVerifyValidationFailedEventSubsystem = "dapp-sdk"
	Wallet    BridgeVerifyValidationFailedEventSubsystem = "wallet"
	WalletSdk BridgeVerifyValidationFailedEventSubsystem = "wallet-sdk"
)

// Defines values for BridgeVerifyValidationFailedEventVerifyType.
const (
	BridgeVerifyValidationFailedEventVerifyTypeConnect BridgeVerifyValidationFailedEventVerifyType = "connect"
)

// BridgeClientConnectErrorEvent The event is fired on SSE connection failure or unexpected disconnect.
type BridgeClientConnectErrorEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeClientConnectErrorEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// ErrorCode Error code.
	ErrorCode *int `json:"error_code,omitempty"`

	// ErrorMessage Error message.
	ErrorMessage *string `json:"error_message,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                 `json:"event_id,omitempty"`
	EventName *BridgeClientConnectErrorEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeClientConnectErrorEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeClientConnectErrorEventClientEnvironment The client environment.
type BridgeClientConnectErrorEventClientEnvironment string

// BridgeClientConnectErrorEventEventName defines model for BridgeClientConnectErrorEvent.EventName.
type BridgeClientConnectErrorEventEventName string

// BridgeClientConnectErrorEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeClientConnectErrorEventSubsystem string

// BridgeClientConnectStartedEvent The event is fired when the dApp or wallet initiates the SSE connection via GET /events?client_id=... method.
type BridgeClientConnectStartedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeClientConnectStartedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                   `json:"event_id,omitempty"`
	EventName *BridgeClientConnectStartedEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeClientConnectStartedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeClientConnectStartedEventClientEnvironment The client environment.
type BridgeClientConnectStartedEventClientEnvironment string

// BridgeClientConnectStartedEventEventName defines model for BridgeClientConnectStartedEvent.EventName.
type BridgeClientConnectStartedEventEventName string

// BridgeClientConnectStartedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeClientConnectStartedEventSubsystem string

// BridgeClientMessageDecodeErrorEvent When wallet or dapp receives message from bridge (SSE stream).
type BridgeClientMessageDecodeErrorEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeClientMessageDecodeErrorEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Hash of encrypted message received from the dApp.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// ErrorCode Error code.
	ErrorCode *int `json:"error_code,omitempty"`

	// ErrorMessage Error message.
	ErrorMessage *string `json:"error_message,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                       `json:"event_id,omitempty"`
	EventName *BridgeClientMessageDecodeErrorEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeClientMessageDecodeErrorEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`

	// WalletId Unique wallet ID.
	WalletId *string `json:"wallet_id,omitempty"`
}

// BridgeClientMessageDecodeErrorEventClientEnvironment The client environment.
type BridgeClientMessageDecodeErrorEventClientEnvironment string

// BridgeClientMessageDecodeErrorEventEventName defines model for BridgeClientMessageDecodeErrorEvent.EventName.
type BridgeClientMessageDecodeErrorEventEventName string

// BridgeClientMessageDecodeErrorEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeClientMessageDecodeErrorEventSubsystem string

// BridgeClientMessageReceivedEvent When wallet or dapp receives message from bridge (SSE stream).
type BridgeClientMessageReceivedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeClientMessageReceivedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Hash of encrypted message received from the dApp.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                    `json:"event_id,omitempty"`
	EventName *BridgeClientMessageReceivedEventEventName `json:"event_name,omitempty"`

	// MessageId Message ID.
	MessageId *string `json:"message_id,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// RequestType Request type.
	RequestType *string `json:"request_type,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeClientMessageReceivedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`

	// WalletId Unique wallet ID.
	WalletId *string `json:"wallet_id,omitempty"`
}

// BridgeClientMessageReceivedEventClientEnvironment The client environment.
type BridgeClientMessageReceivedEventClientEnvironment string

// BridgeClientMessageReceivedEventEventName defines model for BridgeClientMessageReceivedEvent.EventName.
type BridgeClientMessageReceivedEventEventName string

// BridgeClientMessageReceivedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeClientMessageReceivedEventSubsystem string

// BridgeConnectEstablishedEvent defines model for BridgeConnectEstablishedEvent.
type BridgeConnectEstablishedEvent struct {
	// BridgeConnectDuration Time spent to connect to the TON Connect bridge (miliseconds).
	BridgeConnectDuration *int `json:"bridge_connect_duration,omitempty"`

	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeConnectEstablishedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                 `json:"event_id,omitempty"`
	EventName *BridgeConnectEstablishedEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeConnectEstablishedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeConnectEstablishedEventClientEnvironment The client environment.
type BridgeConnectEstablishedEventClientEnvironment string

// BridgeConnectEstablishedEventEventName defines model for BridgeConnectEstablishedEvent.EventName.
type BridgeConnectEstablishedEventEventName string

// BridgeConnectEstablishedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeConnectEstablishedEventSubsystem string

// BridgeEventsClientSubscribedEvent When the client subscribed to bridge events.
type BridgeEventsClientSubscribedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeEventsClientSubscribedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                     `json:"event_id,omitempty"`
	EventName *BridgeEventsClientSubscribedEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeEventsClientSubscribedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeEventsClientSubscribedEventClientEnvironment The client environment.
type BridgeEventsClientSubscribedEventClientEnvironment string

// BridgeEventsClientSubscribedEventEventName defines model for BridgeEventsClientSubscribedEvent.EventName.
type BridgeEventsClientSubscribedEventEventName string

// BridgeEventsClientSubscribedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeEventsClientSubscribedEventSubsystem string

// BridgeEventsClientUnsubscribedEvent When the client unsubscribed from bridge events.
type BridgeEventsClientUnsubscribedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeEventsClientUnsubscribedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                       `json:"event_id,omitempty"`
	EventName *BridgeEventsClientUnsubscribedEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeEventsClientUnsubscribedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeEventsClientUnsubscribedEventClientEnvironment The client environment.
type BridgeEventsClientUnsubscribedEventClientEnvironment string

// BridgeEventsClientUnsubscribedEventEventName defines model for BridgeEventsClientUnsubscribedEvent.EventName.
type BridgeEventsClientUnsubscribedEventEventName string

// BridgeEventsClientUnsubscribedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeEventsClientUnsubscribedEventSubsystem string

// BridgeMessageExpiredEvent When the message, sent to the bridge, expires.
type BridgeMessageExpiredEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeMessageExpiredEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Hash of encrypted message received from the dApp.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                             `json:"event_id,omitempty"`
	EventName *BridgeMessageExpiredEventEventName `json:"event_name,omitempty"`

	// MessageId Message ID.
	MessageId *string `json:"message_id,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// RequestType Request type.
	RequestType *string `json:"request_type,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeMessageExpiredEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`

	// WalletId Unique wallet ID.
	WalletId *string `json:"wallet_id,omitempty"`
}

// BridgeMessageExpiredEventClientEnvironment The client environment.
type BridgeMessageExpiredEventClientEnvironment string

// BridgeMessageExpiredEventEventName defines model for BridgeMessageExpiredEvent.EventName.
type BridgeMessageExpiredEventEventName string

// BridgeMessageExpiredEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeMessageExpiredEventSubsystem string

// BridgeMessageReceivedEvent When the bridge receives a message post to /message.
type BridgeMessageReceivedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeMessageReceivedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Bridge encrypted message hash.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                              `json:"event_id,omitempty"`
	EventName *BridgeMessageReceivedEventEventName `json:"event_name,omitempty"`

	// MessageId Message ID.
	MessageId *string `json:"message_id,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// RequestType Request type.
	RequestType *string `json:"request_type,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeMessageReceivedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeMessageReceivedEventClientEnvironment The client environment.
type BridgeMessageReceivedEventClientEnvironment string

// BridgeMessageReceivedEventEventName defines model for BridgeMessageReceivedEvent.EventName.
type BridgeMessageReceivedEventEventName string

// BridgeMessageReceivedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeMessageReceivedEventSubsystem string

// BridgeMessageSentEvent When the bridge sends a message to the SSE client.
type BridgeMessageSentEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeMessageSentEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Hash of encrypted message received from the dApp.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                          `json:"event_id,omitempty"`
	EventName *BridgeMessageSentEventEventName `json:"event_name,omitempty"`

	// MessageId Message ID.
	MessageId *string `json:"message_id,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// RequestType Request type.
	RequestType *string `json:"request_type,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeMessageSentEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`

	// WalletId Unique wallet ID.
	WalletId *string `json:"wallet_id,omitempty"`
}

// BridgeMessageSentEventClientEnvironment The client environment.
type BridgeMessageSentEventClientEnvironment string

// BridgeMessageSentEventEventName defines model for BridgeMessageSentEvent.EventName.
type BridgeMessageSentEventEventName string

// BridgeMessageSentEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeMessageSentEventSubsystem string

// BridgeMessageValidationFailedEvent When the message, sent to the bridge, expires.
type BridgeMessageValidationFailedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeMessageValidationFailedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Hash of encrypted message received from the dApp.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                      `json:"event_id,omitempty"`
	EventName *BridgeMessageValidationFailedEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// RequestType Request type.
	RequestType *string `json:"request_type,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeMessageValidationFailedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`

	// WalletId Unique wallet ID.
	WalletId *string `json:"wallet_id,omitempty"`
}

// BridgeMessageValidationFailedEventClientEnvironment The client environment.
type BridgeMessageValidationFailedEventClientEnvironment string

// BridgeMessageValidationFailedEventEventName defines model for BridgeMessageValidationFailedEvent.EventName.
type BridgeMessageValidationFailedEventEventName string

// BridgeMessageValidationFailedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeMessageValidationFailedEventSubsystem string

// BridgeRequestSentEvent When dApp or wallet POSTs a request to /message. Subsystems dapp, dapp-sdk, wallet, wallet-sdk.
type BridgeRequestSentEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeRequestSentEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EncryptedMessageHash Hash of encrypted message received from the dApp.
	EncryptedMessageHash *string `json:"encrypted_message_hash,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                          `json:"event_id,omitempty"`
	EventName *BridgeRequestSentEventEventName `json:"event_name,omitempty"`

	// MessageId Message ID.
	MessageId *string `json:"message_id,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// RequestType Request type.
	RequestType *string `json:"request_type,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeRequestSentEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`

	// WalletId Unique wallet ID.
	WalletId *string `json:"wallet_id,omitempty"`
}

// BridgeRequestSentEventClientEnvironment The client environment.
type BridgeRequestSentEventClientEnvironment string

// BridgeRequestSentEventEventName defines model for BridgeRequestSentEvent.EventName.
type BridgeRequestSentEventEventName string

// BridgeRequestSentEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeRequestSentEventSubsystem string

// BridgeVerifyEvent When the client sends a verification request to bridge events.
type BridgeVerifyEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeVerifyEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                     `json:"event_id,omitempty"`
	EventName *BridgeVerifyEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeVerifyEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId *string `json:"user_id,omitempty"`

	// VerificationResult Status of verification.
	VerificationResult *string                      `json:"verification_result,omitempty"`
	VerifyType         *BridgeVerifyEventVerifyType `json:"verify_type,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeVerifyEventClientEnvironment The client environment.
type BridgeVerifyEventClientEnvironment string

// BridgeVerifyEventEventName defines model for BridgeVerifyEvent.EventName.
type BridgeVerifyEventEventName string

// BridgeVerifyEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeVerifyEventSubsystem string

// BridgeVerifyEventVerifyType defines model for BridgeVerifyEvent.VerifyType.
type BridgeVerifyEventVerifyType string

// BridgeVerifyValidationFailedEvent When the client sends a verification request to bridge events.
type BridgeVerifyValidationFailedEvent struct {
	// BridgeUrl Bridge URL.
	BridgeUrl *string `json:"bridge_url,omitempty"`

	// ClientEnvironment The client environment.
	ClientEnvironment *BridgeVerifyValidationFailedEventClientEnvironment `json:"client_environment,omitempty"`

	// ClientId A unique session ID.
	ClientId *string `json:"client_id,omitempty"`

	// ClientTimestamp The timestamp of the event on the client side, in Unix time (stored as an integer).
	ClientTimestamp *int `json:"client_timestamp,omitempty"`

	// ErrorCode Error code.
	ErrorCode *int `json:"error_code,omitempty"`

	// ErrorMessage Error message.
	ErrorMessage *string `json:"error_message,omitempty"`

	// EventId Unique random event UUID generated by the sender. Used for deduplication on the backend side.
	EventId   *string                                     `json:"event_id,omitempty"`
	EventName *BridgeVerifyValidationFailedEventEventName `json:"event_name,omitempty"`

	// NetworkId Network id (-239 for the mainnet and -3 for the testnet). Other values should be rejected.
	NetworkId *string `json:"network_id,omitempty"`

	// Subsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
	Subsystem *BridgeVerifyValidationFailedEventSubsystem `json:"subsystem,omitempty"`

	// TraceId ID to aggregate multiple events into one trace. UUIDv7 must be used (first 48 bits must be unix_ts_ms as in the specification). trace_id older than 24h won't be accepted.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId A unique identifier for the user (refer to subsystem session details for more information). May be omitted, in this case it will be generated on the backend side and generated. UUID must be used.
	UserId     *string                                      `json:"user_id,omitempty"`
	VerifyType *BridgeVerifyValidationFailedEventVerifyType `json:"verify_type,omitempty"`

	// Version The version of the sending subsystem.
	Version *string `json:"version,omitempty"`
}

// BridgeVerifyValidationFailedEventClientEnvironment The client environment.
type BridgeVerifyValidationFailedEventClientEnvironment string

// BridgeVerifyValidationFailedEventEventName defines model for BridgeVerifyValidationFailedEvent.EventName.
type BridgeVerifyValidationFailedEventEventName string

// BridgeVerifyValidationFailedEventSubsystem The subsystem used to collect the event (possible values: dapp, bridge, wallet).
type BridgeVerifyValidationFailedEventSubsystem string

// BridgeVerifyValidationFailedEventVerifyType defines model for BridgeVerifyValidationFailedEvent.VerifyType.
type BridgeVerifyValidationFailedEventVerifyType string

// PostDummyBridgeClientConnectErrorEventJSONRequestBody defines body for PostDummyBridgeClientConnectErrorEvent for application/json ContentType.
type PostDummyBridgeClientConnectErrorEventJSONRequestBody = BridgeClientConnectErrorEvent

// PostDummyBridgeClientConnectStartedEventJSONRequestBody defines body for PostDummyBridgeClientConnectStartedEvent for application/json ContentType.
type PostDummyBridgeClientConnectStartedEventJSONRequestBody = BridgeClientConnectStartedEvent

// PostDummyBridgeClientMessageDecodeErrorEventJSONRequestBody defines body for PostDummyBridgeClientMessageDecodeErrorEvent for application/json ContentType.
type PostDummyBridgeClientMessageDecodeErrorEventJSONRequestBody = BridgeClientMessageDecodeErrorEvent

// PostDummyBridgeClientMessageReceivedEventJSONRequestBody defines body for PostDummyBridgeClientMessageReceivedEvent for application/json ContentType.
type PostDummyBridgeClientMessageReceivedEventJSONRequestBody = BridgeClientMessageReceivedEvent

// PostDummyBridgeConnectEstablishedEventJSONRequestBody defines body for PostDummyBridgeConnectEstablishedEvent for application/json ContentType.
type PostDummyBridgeConnectEstablishedEventJSONRequestBody = BridgeConnectEstablishedEvent

// PostDummyBridgeEventsClientSubscribedEventJSONRequestBody defines body for PostDummyBridgeEventsClientSubscribedEvent for application/json ContentType.
type PostDummyBridgeEventsClientSubscribedEventJSONRequestBody = BridgeEventsClientSubscribedEvent

// PostDummyBridgeEventsClientUnsubscribedEventJSONRequestBody defines body for PostDummyBridgeEventsClientUnsubscribedEvent for application/json ContentType.
type PostDummyBridgeEventsClientUnsubscribedEventJSONRequestBody = BridgeEventsClientUnsubscribedEvent

// PostDummyBridgeMessageExpiredEventJSONRequestBody defines body for PostDummyBridgeMessageExpiredEvent for application/json ContentType.
type PostDummyBridgeMessageExpiredEventJSONRequestBody = BridgeMessageExpiredEvent

// PostDummyBridgeMessageReceivedEventJSONRequestBody defines body for PostDummyBridgeMessageReceivedEvent for application/json ContentType.
type PostDummyBridgeMessageReceivedEventJSONRequestBody = BridgeMessageReceivedEvent

// PostDummyBridgeMessageSentEventJSONRequestBody defines body for PostDummyBridgeMessageSentEvent for application/json ContentType.
type PostDummyBridgeMessageSentEventJSONRequestBody = BridgeMessageSentEvent

// PostDummyBridgeMessageValidationFailedEventJSONRequestBody defines body for PostDummyBridgeMessageValidationFailedEvent for application/json ContentType.
type PostDummyBridgeMessageValidationFailedEventJSONRequestBody = BridgeMessageValidationFailedEvent

// PostDummyBridgeRequestSentEventJSONRequestBody defines body for PostDummyBridgeRequestSentEvent for application/json ContentType.
type PostDummyBridgeRequestSentEventJSONRequestBody = BridgeRequestSentEvent

// PostDummyBridgeVerifyEventJSONRequestBody defines body for PostDummyBridgeVerifyEvent for application/json ContentType.
type PostDummyBridgeVerifyEventJSONRequestBody = BridgeVerifyEvent

// PostDummyBridgeVerifyValidationFailedEventJSONRequestBody defines body for PostDummyBridgeVerifyValidationFailedEvent for application/json ContentType.
type PostDummyBridgeVerifyValidationFailedEventJSONRequestBody = BridgeVerifyValidationFailedEvent
