{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Send Receive Msg",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(redis_cluster_messages_received_total{job=\"valkey_exporters\"}[5m])",
     "legendFormat": "Received {{instance}}"
    },
    {
     "expr": "rate(redis_cluster_messages_sent_total{job=\"valkey_exporters\"}[5m])",
     "legendFormat": "Sent {{instance}}"
    }
   ]
  },
  {
   "title": "Total Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"valkey_exporters\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(redis_connected_clients{job=\"valkey_exporters\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "redis slots assigned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "redis_cluster_slots_assigned{job=\"valkey_exporters\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consolidated TX/RX rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=~\"valkey-shard.*\"}[1m])\n)\n",
     "legendFormat": "RX {{container_label_com_docker_compose_service}}"
    },
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=~\"valkey-shard.*\"}[1m])\n)\n",
     "legendFormat": "TX {{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}